### ISSUE TITLE
这个论坛谁创建的啊。。 by 540625404

### ISSUE THREAD

**Issue by freizl** [HaskellCNOrg/haskellcn#106]
---------------------------------------
这个论坛谁创建的啊。。

报到

__有人在吗？__

---------------------------------------

**Comment by SnowOnion** [comment]
感谢长期维护 http://www.haskellcn.org，以及在不维护 http://a.haskellcn.org/ 之后把帖子转移到 issue :D

**Comment by SnowOnion** [comment]
感谢长期维护 [http://www.haskellcn.org](http://www.haskellcn.org)，以及在不维护 http://a.haskellcn.org/ 之后把帖子转移到 issue :D
