### ISSUE TITLE
如何安装GHC？ by eacho87

### ISSUE THREAD

**Issue by freizl** [HaskellCNOrg/haskellcn#131]
电脑装的是windows系统10，系统显示是64位，网站上下载了64位full版本解压，把temp文件夹里的四个文件逐个安装后，在命令提示符还是调运不出GHCI程序，提示语是：ghci不是内部或外部的命令，也不是可运行的程序或批处理文件，电脑也重启了，还是不行，难道我该装32位的试试？

**Comment by haskio** [comment]
现在只能通过choco来安装了。
之前应该还可以通过下载安装包来进行，可能一些下载站还有，lz可以找找
另外独立安装包貌似还带winghci 还是很好用的。

**Comment by YouWillBe** [comment]
> 现在只能通过choco来安装了。
> 之前应该还可以通过下载安装包来进行，可能一些下载站还有，lz可以找找
> 另外独立安装包貌似还带winghci 还是很好用的。

最好还是wsl里面装，别纠结windows了
