### ISSUE TITLE
哪位大牛解释一下Real World Haskell第95页的myFoldl函数是怎么回事呗。。。想了好久，写写画画了好久，理解不了啊。 by btnz

### ISSUE THREAD

**Issue by freizl** [HaskellCNOrg/haskellcn#132]
Real World Haskell第95页
In fact, we can even write foldl using foldr!
--file: ch04/Fold.hs
myFoldl :: (a -> b -> a) -> a -> [b] -> a
myFoldl f z xs = foldr step id xs z
    where step x g a = g (f a x)

**Comment by zwvista** [comment]
看我的博客
Haskell语言学习笔记（3）map, filter, fold
https://blog.csdn.net/zwvista/article/details/54747749
