### ISSUE TITLE
Haskell要是改成这样就好了 by iwon

### ISSUE THREAD

**Issue by freizl** [HaskellCNOrg/haskellcn#136]
1.定义函数时的“=”前加个冒号":"，方便区分参数和函数体。
如：
sum : : Int -> Int -> Int ->Int
sum a b c = a+b+c       （好像是c=a+b+c)
改为：
sum : : Int -> Int -> Int ->Int
sum a b c  ：= a+b+c
"：" 表示函数参数结束，后面跟等号表示函数体开始

2.[2*n | n<-[2,4,7],n>3] 改为：[ n<-[2,4,7],n>3 | 2*n  ] 或 [ [2,4,7]->n,n>3 | 2*n  ] ，"|" 左边表示可输入的元素，右边表示输出
如：
addpairs : : [(Int, Int)] -> [Int]
addpairs  pairList  ：=[ pairList->(m,n) , m<n | m+n ]

**Comment by GordonGgx** [comment]
多此一举

**Comment by Garriot** [comment]
第一个没必要。加完以后 := 和= 是完全等价的，而且现在并没有会出现=歧义的情况。
第二个现在的写法和数学定义是一样的。
