### ISSUE TITLE
安装 ghc-mod 冲突，求不冲突的版本

### ISSUE THREAD

**Issue by rarpainting** [HaskellCNOrg/haskellcn#143]
```shell
➤ stack --version
Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0
```
安装 ghc-mod, 本来设了 allow-newer , 但是跳 bug 了，想着还是装低版本, 想问下
怎么安装特定版本，你们用的版本都是那些？
谢谢

**Comment by freizl** [comment]
@rarpainting 
我没装过ghcmod 貌似不支持8.2以上，你默认用stack lts resolver是那个版本，看起来 9.21或以下 可能可以？
