### ISSUE TITLE
关于维护论坛之事

### ISSUE THREAD

**Issue by kalxd** [HaskellCNOrg/haskellcn#144]
这事一直没忘，上班后连学习haskell时间都没了。

snap官方网站翻来覆去看了几遍，依然看不懂。试过用yesod和mongo重写，过程也不算特别顺利。写页面太难了。
看着隔壁[rust中文论坛](https://github.com/rustcc/forustm)，好像挺容易的。

请问你有什么好的建议吗？

**Comment by kalxd** [comment]
想要继续维护Haskell论坛。
上面说的都是客观原因，可能是基础太差，有些力不从心。
打算用yesod + postgresql重头做一个，不知道服务器上支不支持postgresql数据库。这次可能真要8102年才能完成。

**Comment by SnowOnion** [comment]
现在[知乎（Haskell 话题）（时间排序）](https://www.zhihu.com/topic/19593103/newest)可以说是事实上的“Haskell 中文论坛”……

还有藏在“暗网”里的——这里仅指搜索引擎找不到——比如 Haskell QQ 群，最大的是 72874436，接近一千人；还有一些小的，可以用手机 QQ 的*群搜索*找到。

**Comment by kalxd** [comment]
也对，Haskell很小众，做了未必能有多少好处。

**Comment by kalxd** [comment]
https://coderplanets.com/haskell/posts
@freizl 不介意的话就用这个。

**Comment by freizl** [comment]
@kalxd 打不开。看起来还是github issue简单点

**Comment by kalxd** [comment]
> 
> 
> @kalxd 打不开。看起来还是github issue简单点

网站打不开还是什么？上面目前还未有人发帖。
