### ISSUE TITLE
手把手教你做λ - 引言 by ninegua

### ISSUE THREAD

**Issue by freizl** [HaskellCNOrg/haskellcn#17]
《手把手教你做λ》是一个 tutorial 系列，面向正在学习 Haskell 编程的程序员。如果你缺乏对 Haskell 的最基本概念，我建议还是从正式全面的教材开始，比如 [Learn You a Haskell for Great Good!]

换句话说，这个系列不会教你如何使用正确的语法编写 Haskell 程序，而是如何提高 Haskell 编程的水平
。在开始的时候，你可以没有学过这门语言，甚至是编程新手。但是随着我们内容的展开，你应该能够独立
从 Haskell 的书本上学习到相关基础知识，并参与到本教程中来。

这个系列之所以叫做《手把手教你做λ》，是因为我们的目的是最终用 Haskell 实现一个 Lambda 表达式的
计算器，作为 CGI 程序运行在网站上，最后的效果参见 [Lambda Viewer]。如果你还不知道什么是 Lambda Calculus，那我们正好一起把它也给学了，因为它是所有函数语言的理论基础与核心。

本系列希望涵盖的内容有：algebraic datatype，recursion，higher-order function，polymorphism，type class，data traversal，monad，functor，applicative，monad transformer，generics，以及 Parsec 等常见库的使用，DSL (domain specific language) 的实现等等。

每一课的内容不多，只会涉及一个知识点甚至更少。会介绍一定的背景知识，并包含少量习题。我尽量做到
两到三日一更，持续至少一到两个月。这样大部分人每次用少量时间就可以跟上进度，想多学一点的则可以
同时精读正规教材。

主要是希望大家能够积极参与讨论和动手实践，越多的互动越好。毕竟学习一门新的编程语言不仅仅是学习
它语法规则和库的使用而已，还要能够用新的方式来思考，来抽象，来表达，来抓住问题的核心并解决它，
从而完成一次自我的提升。这是每一个优秀的程序员的基本素养。

[Lambda Viewer]: http://projectultimatum.org/cgi-bin/lambda
[Learn You a Haskell for Great Good!]: http://learnyouahaskell.com

**Comment by freizl** [comment]
来学习Haskell了。

**Comment by HoyanMok** [comment]
迁移的时候链接出问题了，给大家重新整理了一份

-     [引言](https://github.com/HaskellCNOrg/haskellcn/issues/17)
-     [（一）关于λ表达式的一切](https://github.com/HaskellCNOrg/haskellcn/issues/19)
-     [（二）数据类型的结构与解构](https://github.com/HaskellCNOrg/haskellcn/issues/20)
-     [（三）漂亮打印与数学归纳法](https://github.com/HaskellCNOrg/haskellcn/issues/26)
-     [（四）语法识别器、高阶函数和列表推导](https://github.com/HaskellCNOrg/haskellcn/issues/50)
-     [（五）语法识别器的拼接与组合](https://github.com/HaskellCNOrg/haskellcn/issues/60)
-     [（六）如何正确识别λ表达式](https://github.com/HaskellCNOrg/haskellcn/issues/94)
-     [（七）从形式语义到等价关系](https://github.com/HaskellCNOrg/haskellcn/issues/126)
-     [（八）替换与归约](https://github.com/HaskellCNOrg/haskellcn/issues/137)
