### ISSUE TITLE
如何理解“证明即程序、结论公式即程序类型”？

### ISSUE THREAD

**Issue by zzz6519003** [HaskellCNOrg/haskellcn#170]

**Comment by SnowOnion** [comment]
常伴随着“证明即程序、结论公式即程序类型”的 slogan 出场的 Curry-Howard Correspondence（柯里-霍华德对应、CH 对应）可以以很多种“面貌”出现，比如 自然演绎系统里的证明 与 Lambda 演算里的程序 的对应，比如 希尔伯特风格公理系统里的证明 与 组合子演算里的程序 的对应。选定一种“面貌”之后，CH 对应也可以以不同的复杂程度出现，可以只考虑简单的情形而不妨碍体验到 CH 对应的美妙。以 自然演绎-Lambda 演算 为例，可以只考虑 【直觉主义命题逻辑的蕴含词片段的自然演绎（有时记作 $Ni_\{\to\}$）】-【只含有基本类型和函数类型 T→T 的简单赋类 Lambda 演算（有时记作 $\lambda_\to$）】这一简单情况。

学习这个简单情况的一个办法是：读 Basic Proof Theory 第二版（ https://book.douban.com/subject/2006104/ ），从头撸到第 26 页的下图所示的例子，应该就明白噜。稍展开解释就是：(A->B->C)->(A->B)->A->C 这个 formula 在自然演绎里的如图所示的证明树，可被“无损地”表示为 λuvw.uw(vw)；而如果把 λuvw.uw(vw) 当成简单赋类 Lambda 演算里的项，对它做类型推断的结果恰好是 (A->B->C)->(A->B)->A->C 这个 type。

（注：我假定读者熟悉“箭头是右结合的”，所以我比起书上省略了更多括号）

<img width="506" alt="image" src="https://user-images.githubusercontent.com/1908576/76163425-dfff9a80-6180-11ea-86e9-38a0051b6926.png">

**Comment by zzz6519003** [comment]
看不太懂 谢谢！

**Comment by SnowOnion** [comment]
略微修改了措辞。@zzz6519003
