### ISSUE TITLE
首页该更新了

### ISSUE THREAD

**Issue by ksqsf** [HaskellCNOrg/haskellcn#173]
> 20多年尖端研究

已经是 30 多年了 :)

> IRC

#haskell 已经转移到 Libera Chat，建议这里的链接也转移到 Libera Chat。

**Comment by freizl** [comment]
1. Updated
2. Remove IRC but may come back later.

**Comment by jiyinyiyong** [comment]
额, 顺着网址过来看了一眼...

这边还有个组呢 https://github.com/fp-china/fp-china.org/discussions 不过也没人..
