### ISSUE TITLE
Haskell 题目求助！编写一个递归函数

### ISSUE THREAD

**Issue by xiussr** [HaskellCNOrg/haskellcn#175]
假设我们想要实现一个决策树。 当应用于某些对象时，决策树将应用一系列条件并根据结果返回true或false。  例如，当应用该决策树时，一盒4个香蕉将返回false，一盒3个苹果将返回true。  

以下数据定义为任何泛型类型的对象a定义了这样的决策树:  

data DTree a = Leaf Bool | Node (a->Bool) (DTree a) (DTree a) 

这是决策树的一个实现  

d1 :: DTree FruitBox

d1 = Node (\(f,_)-> f==Apple) (Node (\(_,n)-> n>3) (Leaf False) (Leaf True)) (Leaf False)

使用递归来编写一个函数applyDTree，它将把一个决策树应用到一个对象上，以返回一个布尔值。 例如,  

applyDTree d1 (Banana,4) will return False and applyDTree d1 (Apple,3) will return True

你的函数需要是多态的，也就是说，它可以在任何类型上使用。

**Comment by freizl** [comment]
- `(Banana,4) will return False`, is it because `f==Apple` is false?
- `d1 (Apple,3) will return True` why this is true?
