### ISSUE TITLE
haskell

### ISSUE THREAD

**Issue by xiussr** [HaskellCNOrg/haskellcn#176]
Haskell如何判断一个数列为等差数列？

**Comment by xiaolzha** [comment]
```haskell
import Data.List ( nub )

a :: [Int]
a = [1, 3, 5, 7, 9, 11]

b :: [Int]
b = [2, 4, 6, 8, 10, 11]

check :: [Int] -> Bool
check l = (==) 1 $ length $ nub $ zipWith (-) (init l) (tail l)

main :: IO ()
main = do
  print $ show $ check a
  print $ show $ check b

```

**Comment by yushuaizhao** [comment]
main = print $ check [1,2,3,4,5]

diff :: (Num a) => [a] -> [a] 
diff xs = zipWith (-) (tail xs) (init xs) 

check xs = all (== 0) $ diff $ diff xs

**Comment by yushuaizhao** [comment]
`
main = print $ check [1,2,3,4,5]

diff :: (Num a) => [a] -> [a] 
diff xs = zipWith (-) (tail xs) (init xs) 

check xs = all (== 0) $ diff $ diff xs
`
