### ISSUE TITLE
haskell help!

### ISSUE THREAD

**Issue by xiussr** [HaskellCNOrg/haskellcn#177]
data DTree a = Leaf Bool | Node (a->Bool) (DTree a) (DTree a)
Use DTree to construct a decision tree d4 that takes a generic decision tree as an argument and returns True if and only if all leaf nodes in the decision tree have the value True. Include the type declaration for d4.
Hint: Use an auxiliary function to determine if all the leaf nodes in a decision tree are True.

使用DTree构造一个决策树d4，它以一个通用的决策树作为参数，当且仅当决策树中的所有叶子节点的值都为True时返回True。 包括d4的类型声明。  
提示:使用辅助函数来确定决策树中的所有叶节点是否为True。

**Comment by freizl** [comment]
dup with https://github.com/HaskellCNOrg/haskellcn/issues/175

**Comment by zzz6519003** [comment]
> dup with #175

dup?
