### ISSUE TITLE
Fork haskell.org into an Chinese version

### ISSUE THREAD

**Issue by freizl** [HaskellCNOrg/haskellcn#2]
https://github.com/haskell-infra/hl

**Comment by kxxoling** [comment]
试着汉化了下官方的 hl 库：https://github.com/kxxoling/hl/tree/chs
但是这一句的意思不清楚：Run this every time you want to update the web handler in-place, as in this demo.

@Garriot  暂时在这里讨论吧。BTW，在中文社区用英文讨论不太有必要的样子。

**Comment by Garriot** [comment]
不好意思，我刚才的机器没有中文输入法

我在想翻译官网的必要性有多大，毕竟只是翻译一个门面上的中文。官网最有价值的是背后那些文档。
我觉得可以讨论一下是不是有更有必要的计划，比如几篇关键文档的翻译，把九瓜老师的lambda教程整理一下

**Comment by kxxoling** [comment]
我主要是觉得官网很好看，结构也比现在的丰富，对于我这样的外观党来说，好的官网非常重要！ :)

**Comment by Garriot** [comment]
OK。“翻译”的意思就是把官网的文本汉化，还是要把i18n加上去？

**Comment by Garriot** [comment]
"Run this every time you want to update the web handler in-place, as in this demo." 可不可以翻译为“如果你想要web handler的改动（在GHCi内）即刻生效，需执行此命令。详情可见<demo>”

**Comment by kxxoling** [comment]
我觉得第一版完成后就可以分道扬镳了，官网那个有很多独有的信息，中文这个最好是用中文世界的等价物替换掉，比如托管服务赞助商、讨论论坛等等。

翻译这里我主要是不理解这个 web handler 代表什么。demo 里面是一整个项目，估计这里的意思是说“如 demo 中使用教程所说”。

**Comment by Garriot** [comment]
web handler我认为就是会反应在网站上的变化，在GHCi里需要用DevelMain.update load一下改动。 demo讲得就是DevelMain reload的demo

**Comment by freizl** [comment]
倒是官网界面设计还是蛮好看的，可以把能翻译的翻译过来，然后有中文的有价值的往上加。

**Comment by freizl** [comment]
@kxxoling 邀请你加入https://github.com/HaskellCNOrg/hl 这个了，直接把你的改动push上来

**Comment by kxxoling** [comment]
@freizl 嗯，我看到了。View 里是用于生成的，不过在 Atom 下看着不是很清楚，Haskell 有好用的 IDE 或者编辑器支持吗？

**Comment by freizl** [comment]
有个Leksah听说还不错 我没用过，我用Emacs ＋ Haskell Mode

**Comment by kxxoling** [comment]
@freizl 不会 Emacs。。Leksah 下载中，好慢。。。我还是先用 Vim + HaskellMode 吧。。。

**Comment by Garriot** [comment]
sublime text 3 + sublimeHaskell 插件

或者IDEA ＋ Haskell插件（但不太稳定）
