### ISSUE TITLE
网站不维护了吗？

### ISSUE THREAD

**Issue by lanzhiheng** [HaskellCNOrg/haskellcn#3]
1. 发现网站好像用户量还是比较少。
2. 好久没有维护了？还是有新的中国社区站点？ 👍

**Comment by freizl** [comment]
主要由于工作关系，好长时间没有维护。。惭愧。。
用户少倒是一直来的现象，没有太推广。。

**Comment by lanzhiheng** [comment]
我也是刚接触haskell没多久，在中国用这玩意的地方并不多。不过感觉它算是函数式语言里面用得算是比较多的。 中国Erlang的倒是有见到。

**Comment by freizl** [comment]
最近几年Haskell的出现率还是不错的，Erlang没接触过，听说在多线程领域很强？

**Comment by lanzhiheng** [comment]
erlang我也没怎么接触，之前有听过游戏公司用的比较多。Haskell是无意中接触的， 之前只是稍微写过一点Elisp。 😢 觉得函数式这个玩意比较过瘾。

**Comment by freizl** [comment]
是蛮过瘾的！！
