### ISSUE TITLE
惰性计算这样的特性当初是怎么提出来的？ by Liutos

### ISSUE THREAD

**Issue by freizl** [HaskellCNOrg/haskellcn#40]
Haskell有惰性计算，好像是从Miranda那里来的特性吧？这种特性是谁提出来的呢？是用来解决什么问题的呢？难道是像《SICP》里面那样子用来解决效率问题的？

**Comment by freizl** [comment]
纯粹挖链接:  
http://en.wikipedia.org/wiki/Lazy_evaluation#History
> Lazy evaluation was introduced for the lambda calculus by (Wadsworth 1971) and for programming languages independently by (Henderson & Morris 1976) and (Friedman & Wise 1976).[6]

http://en.wikipedia.org/wiki/Graph_reduction

> In computer science, graph reduction implements an efficient version of non-strict evaluation, an evaluation strategy where the arguments to a function are not immediately evaluated. This form of non-strict evaluation is also known as lazy evaluation and used in functional programming languages. The technique was first developed by Chris Wadsworth in 1971.

http://en.wikipedia.org/wiki/Graph_reduction#History
> The concept of a graph reduction that allows evaluated values to be shared was first developed by Chris Wadsworth in his 1971 Ph.D. dissertation.[1] This dissertation was cited by Peter Henderson and James H. Morris Jr. in 1976 page, “A lazy evaluator” [1] that introduced the notion of lazy evaluation. In 1976 David Turner incorporated lazy evaluation into SASL using combinators.[2] SASL was an early functional programming language first developed by Turner in 1972.

**Comment by freizl** [comment]
居然是学术上来的东西？！

**Comment by freizl** [comment]
@Liutos 数学是我软肋, 但现在想按 Wiki 说的,  
Haskell 明明为研究 FP 而设计的数学语言, 初衷不是编程语言,  
那么 hs 数学基础不会少.. 想到这点觉得费心思了

**Comment by freizl** [comment]
链接我没看，建议你看看http://research.microsoft.com/en-us/um/people/simonpj/papers/history-of-haskell/history.pdf
http://www.cs.nott.ac.uk/~nhn/G54FOP/LectureNotes/lecture11.pdf
Haskell想起初想结束过多函数语言的混战。
由于Call by value会以相对少的步骤来计算结果，但不一定会停止, call by need用很多多余的步骤计算结果，但如果停止它一定会停。
比如 const 5 [1..]，call by name 不会计算参数[1..]的值。但call by value是这里计算[1..]，这个函数就不会停止了。
为了保证计算的速度的同时让那些能停止的计算最终会停下来，于是就引入了Lazy Evaluation

**Comment by freizl** [comment]
CONS should not Evaluate its Arguments
https://www.cs.indiana.edu/cgi-bin/techreports/TRNNN.cgi?trnum=TR44

**Comment by freizl** [comment]
惰性 (lazy) 计算和严格 (strict) 计算都是从 [λ 演算](http://en.wikipedia.org/wiki/Lambda_calculus) 里面来的。一个 λ 表达式里可能有多处 redex (能够进行β-规约的地方) 可以做 β-规约，如何选择先做哪一个是个策略问题。通常的两种方式：

1. applicative order: 总是对最右边最内层的 redex 进行 β-规约
2. normal order: 总是对最左边最外层的 redex 进行 β-规约

在 λ 演算里常用的实际上是 normal order，因为 Church-Rosser 定理证明了如果一个 λ 表达式存在范式的话，那么 normal order 规约一定能够停止在这个范式上。而 applicative order 的规约方式并不总是能够停下来 (也就是说，applicative order 无法确保得到范式)。

判断规约算法效率的标准之一，是看它最终得到范式时进行了多少步的 β-规约。我们可以找出各种例子来证明：对某些表达式，normal order 的 β-规约次数少于 applicative; 对于另一些表达式，applicative 则少于 normal。所以在效率方面，normal order 和 applicative order 并没有哪个是稳占优势的。

由这两种规约的策略衍生出来的两种[求值策略](http://en.wikipedia.org/wiki/Evaluation_strategy)：（化简是从表达式到表达式，求值是从表达式到值。如果我们只考虑没有常量的 λ 演算，那么只有一种值，即数学意义上的函数）

1. call-by-value: 先对函数的参数求值，再把参数替换成值，代入函数体形成新的表达式，再求值。
2. call-by-name: 先不对函数的参数求值，而是直接将参数所对应的表达式代入函数体形成新的表达式，再求值。

applicative order/normal order 和 call-by-value/call-by-name 的区别还在于，后者不对函数体的内部进行计算，因为它们认为函数的值就是它本身，所以无需进一步求值。

注意到 call-by-name 里面有一个“将函数体里面的形参替换成实参表达式”的概念，基本上可以理解为 "copy"。但是我们知道，对于任意一个给定的 λ 表达式，求值无副作用，它的值也不会变，所以多次计算同一个实参表达式 (因为可能被 "copy" 了很多份) 的值实际上是一种浪费。

这时就引入了所谓 call-by-need 的概念，并不直接 "copy"，而是把对应的表达式放在 heap 上，求过一次值之后就用值来替换这个表达式。这样，对一个形参所代表的表达式最多只求一次值，也就是通常我们说的惰性 (lazy) 求值。而通常所说严格 (strict) 求值，指的就是 call-by-value.

有意思的是 Haskell Report 并不要求一定用 lazy 方式来实现 Haskell，而是说 "non-strict"，这里很有一点想象空间。

有一个常见的错误概念，就是认为 lazy，或者说 call-by-need 更有效率，因为它没有浪费时间在不需要求值的参数上。但是从语言实际的实现上讲，lazy 的算法更复杂，overhead 更多，所以往往不会有 call-by-value 快。

那 lazy 的好处到底在哪里？是因为它 (无论是 call-by-name 还是 call-by-need) 能够保证求值过程中总是在做等价变换，这对于保持程序正确有相当大的帮助，可以很灵活地进行各种等价替换和优化处理，不必担心程序的正确性出问题。而且因为 call-by-need 有一定的效率保障（对一个参数最多求值一次），所以程序的复用度相当高，很少需要担心因为使用了函数组合而丢失了效率。

最后，还存在一种求值方式，总是能够保证用到的 β-规约次数最少，叫 optimal evaluation，也是一种 non-strict 的求值方式，和 call-by-name/call-by-need 一样可以保证总是等价变换。它的实现方法比 call-by-need 复杂很多倍，而且迄今也没有什么好方法提高效率，属于较冷门的研究领域。

**Comment by zzz6519003** [comment]
@Liutos 召唤！
