### ISSUE TITLE
学 Haskell 应该走哪几个过程?

### ISSUE THREAD

**Issue by freizl** [HaskellCNOrg/haskellcn#7]
> 测试帖.. 发现预览功能和标签和 CNode 上对比是不是 bug  
`Uncaught ReferenceError: $ is not defined` Chrome 上报错  

搭上自我介绍.. 小弟大三, 学不好数学和 C, 于是在网上翻资料想学玩代码. Linux 党.  
入门的时候绕几种语言, 后来为了语法去熟悉了 Haskell, 没能深入..  
接触函数式编程后 CoffeeScript 就感觉顺多了, 就很浅地开始玩 Node  

特别喜欢的还是 Haskell, 但一直都有种太高无法接近的感觉  
所以特别想了解开始学 Haskell, 基础语法之后, 怎样开始深入学和写实用的代码?  
还有比方入门的时候应该从哪些代码进行练习熟悉和掌握?  
然后这后面又应该从什么方面继续接触 Haskell 深入的东西?

**Comment by ZoomQuiet** [comment]
和其它语言的自学一样,
初步了解后, 上手写一个实用工具才能真正深入

2018-04-30 15:48 GMT+08:00 Haisheng, Wu <notifications@github.com>:
> 测试帖.. 发现预览功能和标签和 CNode 上对比是不是 bug
> Uncaught ReferenceError: $ is not defined Chrome 上报错
>
> 搭上自我介绍.. 小弟大三, 学不好数学和 C, 于是在网上翻资料想学玩代码. Linux 党.
> 入门的时候绕几种语言, 后来为了语法去熟悉了 Haskell, 没能深入..
> 接触函数式编程后 CoffeeScript 就感觉顺多了, 就很浅地开始玩 Node
>
> 特别喜欢的还是 Haskell, 但一直都有种太高无法接近的感觉
> 所以特别想了解开始学 Haskell, 基础语法之后, 怎样开始深入学和写实用的代码?
> 还有比方入门的时候应该从哪些代码进行练习熟悉和掌握?
> 然后这后面又应该从什么方面继续接触 Haskell 深入的东西?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
life is pathetic, go Pythonic! 人生苦短, Python当歌!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization learning!

**Comment by freizl** [comment]
@ZoomQuiet 谢谢你的关注，我正在做数据迁移，可能会造成一些疑惑！
